spring:
  config:
    active:
      on-profile: prod
  datasource:
    url: ENC(rv7cbtcwgQddGWQ6zbxL7348Q08COBnvw3EXV2QvcKbcOSTGx3IdRNJ7u4qwRZV1dowGb1UyaRewwvwVabhU2g==)
    username: ENC(5g7QwLq0KlEt1EjjanVtVvVYcyiXq+Lo)
    password: ENC(tPiBP8C0yCIluTb2x0d+ibvyp99IC3Ek)
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

logging:
  config: classpath:log4j2-prod.xml
  level:
    org:
      hibernate:
        SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: false

file:
  dir: /app/

base:
  url: ENC(0hBajist2KGxFqDz6EaPfq2Tkk0edfA2ZMhs54JEpcDpzCvXdGBARA==)

server:
  port: ENC(C7J98t9dzMaStIHiyEvOvA==)
  ssl:
    enabled: true
    key-store: /ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(Wes8r4kIFAJt8f/sGpOQDH1o0TtjpTZq)
