spring:
  config:
    active:
      on-profile: prod
  datasource:
    url: PvhVzk13uUMQH2SMUlZZXnRT1HFtenZSup/jCHfNDC6ilCeBBrYt6f+jTwWFUwJdYvtAnODSPdY=
    username: 5g7QwLq0KlEt1EjjanVtVvVYcyiXq+Lo
    password: wsA8utco+CJqQiuDDwG1angHw4aA1Xol
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        default_batch_fetch_size: 100
  #logging.level:
  #org.hibernate.SQL: debug
  #org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

file:
  dir: /app/

logging:
  config: 4VVZhSCBwQOx/xew0yBfzUczND/QwDoOM0ECcQIfUpolFVSpz9ekHw==

base:
  url: gGWykxlqG4A1WYxL9ZEMDXDX4o3RlVARSRflYePYfpJbC7/Sp+wCGw==
