spring:
  config:
    active:
      on-profile: prod
  datasource:
    url: ENC(PvhVzk13uUMQH2SMUlZZXnRT1HFtenZSup/jCHfNDC6ilCeBBrYt6f+jTwWFUwJdYvtAnODSPdY=)
    username: ENC(5g7QwLq0KlEt1EjjanVtVvVYcyiXq+Lo)
    password: ENC(wsA8utco+CJqQiuDDwG1angHw4aA1Xol)
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        default_batch_fetch_size: 100
  #logging.level:
  #org.hibernate.SQL: debug
  #org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true

file:
  dir: /app/

logging:
  config: ENC(4VVZhSCBwQOx/xew0yBfzUczND/QwDoOM0ECcQIfUpolFVSpz9ekHw==)

base:
  url: ENC(gGWykxlqG4A1WYxL9ZEMDXDX4o3RlVARSRflYePYfpJbC7/Sp+wCGw==)
