spring:
  profiles:
    active: local
jwt:
  secret: ENC(ZnDWac8QQ6LV1uL8NDXUQU8hwC3LnIm9x0hW6MwUfRchfbe865G0n+RgZobQaNBRyKN745HbSSweGDx7OCMPjIte07+NVM/dLmkCNUq9pMnRFNe+uQdGOurm+7zw7zO3CSLruGb6/Ve2BbN59JNpBhfPU9yeU58+al7XbpYcsFaQ8XVmyvlYqtfocDistWKYAXW6NYoT1cTcj2suUCl/Gdo9h4QTtdW0P+Nja2n9c0L+IRVYLU6kBcy/6+ZJbqg4blfH9jLXhOEZFpE8a5ki9Jvg8/OR1vLk/dqGv4B574gDvQML2hzlm6XeBlWFmcdxMjNM3uYQEbjbgCAGzwktuXs/uBkeqKbHkaIHXIrzcC302R0xJYVq5SDpm5ne+fPZo8oWvrghwzXlvb3Du/wny+HpguVNMm1FGWL+g3HP4Cv2K/0SPB739kyk4lnCR6DRRoTe/1aQmDpmeCtZkCgV0FEfaHsHrYstOENDzedFyySnWJRK5aen8D9turOjGcCu28ga7Ebc1IpP/s4muXj2GSZZRY3T3uNtDYVudjThVvfJic+15m7fhcnl7O1MnjLkUMVN5wvEqt50xJxGoUhVqMxXf1THeAjluO3wb/xW3BzBKmF1YWsWYjJhUPukYdw8jLl6Pm9osdVqfiWKDyqtk/gNKCcIHkCKdUfIYjeOfO1Xi7YEFi+ntbo9pfhHTBI/+R+1ax1xnpx8VRwh64zarcip5zENLeUJpKDiP7uGmpQwe58HXcyiqBGKN3ThIhQpme8vhk/UPH9+jnKuxWA60Xjj9nQdn7CpQHumjyVmOvlHJFNeEhcB4+SA+3fSNDJBxtD7evnoYL1Vy0FPXondTr733WVfSmKBSbTh8K3NWDaYyQDioAaurDy1bHXt5KPWD9rx8c4IEvh4roa1S3+5aFyM3tyMfnLKxMf6Z8aHf/WvoBWYkUW/yh/7bAKyEKr/uxkw97D0IELIJJqDuxYXMVow2F6UrcxPqYAq88wOsLNywBDzD9tUWA==)

jasypt:
  encryptor:
    password: ${jasypt_encryptor_password}

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: jakarta.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
# admin 구글 계정
AdminMail:
  id: ENC(4WFbGs/Cpq6R0agwL5KcTwjaSjiAj70VDXZz5NuuYBKNMvP5xK1p4Q==)
  password: ENC(JO0PmvGxfFhiC2MoGXQhf8F0qzYlAz1oa+RBWM/4J3Y=)

SeoulAPI:
  key: ENC(+Mx7QTrmkA8/U/sVg17P5HZ/ZpBEU49acadiNGyBe2tnF4HgzUUVWQ==)
