spring:
  profiles:
    active: local
jwt:
  secret: ENC(RrFQdT/29kKH4QveaTJYCGLC284gxRS7mIv0dBQS9X/kPdb0OPOfG6li+jakRHv4BMg7K76CTzkAfvUaGSQsa9Y1I/cqLQobIcCgommOXHcADIEPWj9/Pja3l5lC7+wjIcJxMw8Tqc1e+7qDPWeEVlG8wDu7yfhz9Mj12WBcAGZlJEZKuTY7lDFs6NcU+JI87V8nPPxN2meoZCwmv/+WriASpROnmhmpzDAfd4JLfs2qDwzHsMJF2Q==)

jasypt:
  encryptor:
    password: ${jasypt_encryptor_password}

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: jakarta.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465
# admin 구글 계정
AdminMail:
  id: ENC(4WFbGs/Cpq6R0agwL5KcTwjaSjiAj70VDXZz5NuuYBKNMvP5xK1p4Q==)
  password: ENC(JO0PmvGxfFhiC2MoGXQhf8F0qzYlAz1oa+RBWM/4J3Y=)

SeoulAPI:
  key: ENC(+Mx7QTrmkA8/U/sVg17P5HZ/ZpBEU49acadiNGyBe2tnF4HgzUUVWQ==)
