spring:
  config:
    active:
      on-profile: local
  datasource:
    url: ENC(OvXrkqK5y37y5anSoeiWh4FtK7aR5RGaSKFARID6He/IcmJ6lJioyh/8yqMpu+2hxrAxChWmfmdjqcn4hetRf18t1C59k+ar67HmzDo8TCgkVfy0Lmx9cbAHvaTeOXpQ)
    username: ENC(5g7QwLq0KlEt1EjjanVtVvVYcyiXq+Lo)
    password: ENC(tPiBP8C0yCIluTb2x0d+ibvyp99IC3Ek)
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #format_sql: true
        default_batch_fetch_size: 100

logging:
  config: classpath:log4j2.xml
#  level:
#    org:
#      hibernate:
#        SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
